---
- hosts: master
  remote_user: ubuntu
  become: yes
  tasks:
#    - name: Install Docker
#      apt:
#        name:
#          - docker
#          - docker-compose
#        state: present
    - name: Login DockerHub
      shell: docker login -u "{{DOCKER_HUB_USERNAME}}" -p "{{DOCKER_HUB_PASSWORD}}"
    - name: Copy docker-compose file
      copy:
        src: docker-compose.yaml
        dest: /home/ubuntu/
    - name: Copy env file
      copy:
        src: env/pg.env
        dest: /home/ubuntu/
    - name: Restart docker-compose
      shell: |
          docker-compose stop
          docker-compose rm -f
          docker-compose pull
          docker-compose up -d
...
#idempotency